// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLVNZ3OKur4HyNseT6CR1rutFuMiMwCO0',
    appId: '1:916157414952:web:d9577d0fa7119f77777f1d',
    messagingSenderId: '916157414952',
    projectId: 'fir-tutorial-85ab0',
    authDomain: 'fir-tutorial-85ab0.firebaseapp.com',
    storageBucket: 'fir-tutorial-85ab0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUDjjTNtiAYBEev1RwVFxRt1oMZdc2wpo',
    appId: '1:916157414952:android:e7a3072e77588713777f1d',
    messagingSenderId: '916157414952',
    projectId: 'fir-tutorial-85ab0',
    storageBucket: 'fir-tutorial-85ab0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_eKWORX-DF_dBCgWdHtv9vQvNyMQX9ys',
    appId: '1:916157414952:ios:228cc8ea7c09a240777f1d',
    messagingSenderId: '916157414952',
    projectId: 'fir-tutorial-85ab0',
    storageBucket: 'fir-tutorial-85ab0.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_eKWORX-DF_dBCgWdHtv9vQvNyMQX9ys',
    appId: '1:916157414952:ios:228cc8ea7c09a240777f1d',
    messagingSenderId: '916157414952',
    projectId: 'fir-tutorial-85ab0',
    storageBucket: 'fir-tutorial-85ab0.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLVNZ3OKur4HyNseT6CR1rutFuMiMwCO0',
    appId: '1:916157414952:web:5a78e86b67a89f12777f1d',
    messagingSenderId: '916157414952',
    projectId: 'fir-tutorial-85ab0',
    authDomain: 'fir-tutorial-85ab0.firebaseapp.com',
    storageBucket: 'fir-tutorial-85ab0.appspot.com',
  );

}